2020-06-17 17:00:21,345: ERROR: Exception on / [GET] [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py : 1761]
Traceback (most recent call last):
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/app/main/routes.py", line 36, in index
    return render_template('index.html', title = 'Sentiment Analytics', form = form, keysL=keysL, positiveL=positiveL, negativeL=negativeL)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/app/templates/index.html", line 101, in template
    {% block formulario %}{% endblock %}
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/home/g3ek-ar/Escritorio/mySentimentAnalytics/environment/lib/python3.6/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'formulario' defined twice
2020-06-17 17:01:53,487: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:01:53,489: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:01:53,489: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:02:16,425: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:02:16,427: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:02:16,427: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:03:19,882: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:03:19,884: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:03:19,884: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:04:13,578: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:04:13,579: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:04:13,579: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:04:23,016: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:04:23,016: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:04:23,017: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:04:23,017: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:04:25,510: INFO: Iniciando Polarity en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 105]
2020-06-17 17:04:25,510: INFO: Iniciando Polarity en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 105]
2020-06-17 17:04:25,511: INFO: Recuperando recursos [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 109]
2020-06-17 17:04:25,511: INFO: Recuperando recursos [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 109]
2020-06-17 17:04:25,512: INFO: Obteniendo la polaridad [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 115]
2020-06-17 17:04:25,512: INFO: Obteniendo la polaridad [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 115]
2020-06-17 17:05:06,902: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:05:06,904: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:05:06,904: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:05:15,583: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:05:15,583: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:05:15,584: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:05:15,584: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:05:18,143: INFO: Iniciando Polarity en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 105]
2020-06-17 17:05:18,143: INFO: Iniciando Polarity en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 105]
2020-06-17 17:05:18,144: INFO: Recuperando recursos [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 109]
2020-06-17 17:05:18,144: INFO: Recuperando recursos [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 109]
2020-06-17 17:05:18,145: INFO: Obteniendo la polaridad [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 115]
2020-06-17 17:05:18,145: INFO: Obteniendo la polaridad [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 115]
2020-06-17 17:06:15,334: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:06:15,335: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:06:15,335: INFO: mySentimentAnalytics ha iniciado con exito! [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/__init__.py : 33]
2020-06-17 17:06:23,565: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:06:23,565: INFO: Iniciando Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 98]
2020-06-17 17:06:23,566: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:06:23,566: INFO: Iniciando Crawler en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 101]
2020-06-17 17:06:26,090: INFO: Iniciando Polarity en Analytics [in /home/g3ek-ar/Escritorio/mySentimentAnalytics/app/analytics.py : 105]
